spring.application.name=microservicio-productor
server.port=8083

spring.rabbitmq.host=porpoise.rmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=sydwgknf
spring.rabbitmq.password=lb-LE1LVUszCQbmmro04ctWOfKdxSixZ
spring.rabbitmq.virtual-host=sydwgknf